name: Swift

on:
  push:
    branches: [ release/3 ]
  pull_request:
    branches: [ release/3 ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run Tests
      run: xcodebuild -scheme SwiftUICharts test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'
